# This is a basic workflow to help you get started with Actions

name: pipeline

on: [push]

jobs:

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--replace"

  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: rootpass
          POSTGRES_DB: simbirsoft-unique-words-stat
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - run: chmod +x ./gradlew
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: build
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/simbirsoft-unique-words-stat
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: rootpass
